"""Finite symbolic engine over the ternary operation space.

This module is intentionally conservative:
- It does NOT claim to implement a full 3-adic field.
- It does implement a closed finite transformation group acting on {-1,0,1}^9.
- It provides exact, traceable symbolic operations and feedback-pair generation.

The current group is generated by:
- cyclic rotation over the 9 digit positions
- reflection (digit reversal)
- global sign flip

Together these form a finite dihedral-style action with a global negation factor.
That is enough to generate exact symbolic orbits and benchmark whether the learned
representation captures more than the index-derived valuation hierarchy.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import torch

from src.core import TERNARY


@dataclass(frozen=True)
class GroupElement:
    """One exact symbolic transform in the finite group."""

    shift: int
    reflect: bool
    negate: bool

    @property
    def name(self) -> str:
        parts = [f"rot{self.shift}"]
        if self.reflect:
            parts.append("reflect")
        if self.negate:
            parts.append("negate")
        return "+".join(parts)


class FiniteTernaryGroupEngine:
    """Closed symbolic engine for the current ternary operation domain."""

    def __init__(self, n_digits: int = TERNARY.N_DIGITS):
        self.n_digits = int(n_digits)
        self.elements = tuple(
            GroupElement(shift=shift, reflect=reflect, negate=negate)
            for shift in range(self.n_digits)
            for reflect in (False, True)
            for negate in (False, True)
        )

    def apply_element_to_ternary(
        self,
        ternary: torch.Tensor,
        element: GroupElement,
    ) -> torch.Tensor:
        """Apply an exact symbolic group element to ternary digits."""
        transformed = torch.roll(ternary, shifts=element.shift, dims=-1)
        if element.reflect:
            transformed = torch.flip(transformed, dims=(-1,))
        if element.negate:
            transformed = -transformed
        return transformed

    def apply_element_to_indices(
        self,
        indices: torch.Tensor,
        element: GroupElement,
    ) -> torch.Tensor:
        """Apply a group element to operation indices."""
        ternary = TERNARY.to_ternary(indices)
        transformed = self.apply_element_to_ternary(ternary, element)
        return TERNARY.from_ternary(transformed)

    def transformed_index_stack(self, indices: torch.Tensor) -> torch.Tensor:
        """Return all transformed versions of each index.

        Shape:
            (n_group_elements, batch)
        """
        return torch.stack([self.apply_element_to_indices(indices, element) for element in self.elements], dim=0)

    def canonicalize(self, indices: torch.Tensor) -> torch.Tensor:
        """Map each index to a deterministic canonical representative of its orbit."""
        return self.transformed_index_stack(indices).min(dim=0).values

    def choose_non_identity_partner(
        self,
        indices: torch.Tensor,
        seed: int = 321,
    ) -> torch.Tensor:
        """Choose one different orbit member for each input index when possible."""
        transformed = self.transformed_index_stack(indices)
        rng = np.random.default_rng(seed)
        partners: list[int] = []
        indices_cpu = indices.detach().cpu()
        transformed_cpu = transformed.detach().cpu()
        for col, original in enumerate(indices_cpu.tolist()):
            unique = torch.unique(transformed_cpu[:, col])
            options = unique[unique != original]
            if len(options) == 0:
                partners.append(original)
                continue
            pick = int(options[int(rng.integers(len(options)))].item())
            partners.append(pick)
        return torch.tensor(partners, dtype=indices.dtype, device=indices.device)

    def sample_feedback_pairs(
        self,
        indices: torch.Tensor,
        sample_size: int = 2048,
        seed: int = 321,
        match_valuation_negatives: bool = True,
    ) -> dict[str, Any]:
        """Generate exact positive/negative pairs for neurosymbolic feedback loops."""
        rng = np.random.default_rng(seed)
        indices_cpu = indices.detach().cpu()
        valuations = TERNARY.valuation(indices_cpu).cpu()
        canon = self.canonicalize(indices_cpu)

        anchor_count = min(sample_size, len(indices_cpu))
        anchor_pos = np.sort(rng.choice(len(indices_cpu), size=anchor_count, replace=False))
        anchors = indices_cpu[anchor_pos]
        positives = self.choose_non_identity_partner(anchors, seed=seed)

        negatives: list[int] = []
        for anchor, valuation, anchor_canon in zip(
            anchors.tolist(),
            valuations[anchor_pos].tolist(),
            canon[anchor_pos].tolist(),
        ):
            if match_valuation_negatives:
                candidates = torch.where((valuations == valuation) & (canon != anchor_canon))[0]
            else:
                candidates = torch.where(canon != anchor_canon)[0]
            if len(candidates) == 0:
                candidates = torch.where(canon != anchor_canon)[0]
            if len(candidates) == 0:
                negatives.append(anchor)
                continue
            pick_pos = int(candidates[int(rng.integers(len(candidates)))].item())
            negatives.append(int(indices_cpu[pick_pos].item()))

        return {
            "anchors": anchors,
            "positives": positives,
            "negatives": torch.tensor(negatives, dtype=indices.dtype),
            "notes": [
                "Positive pairs are exact orbit partners under the finite transformation group.",
                "Negative pairs are sampled from different symbolic orbits and are matched on valuation when possible.",
                "This engine is a finite group action over ternary words, not a full 3-adic field implementation.",
            ],
        }


TERNARY_GROUP_ENGINE = FiniteTernaryGroupEngine()
