# General Constants
N_TERNARY_OPERATIONS = 19683

# StateNet Controller Constants
STATENET_ANNEALING_STEP = 0.005
STATENET_CONTROLLER_GRAD_PATIENCE = 10
STATENET_CONTROLLER_GRAD_THRESHOLD = 0.01
STATENET_CONTROLLER_PATIENCE_CEILING = 20
STATENET_COVERAGE_FLOOR = 0.95
STATENET_COVERAGE_FIX_THRESHOLD = 0.99      # Fix encoder when coverage drops below this
STATENET_COVERAGE_TRAIN_THRESHOLD = 0.999   # Allow training when coverage is above this
STATENET_HIERARCHY_PATIENCE_CEILING = 30
STATENET_HIERARCHY_PLATEAU_PATIENCE = 15
STATENET_HIERARCHY_PLATEAU_THRESHOLD = 0.001
STATENET_HYSTERESIS_EPOCHS = 5
STATENET_WARMUP_EPOCHS = 10
STATENET_WINDOW_SIZE = 20
